# Generated by Django 5.2 on 2025-05-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_chat_chatmessage_chatparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='last_read_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано пользователями'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_read_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего прочтения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, default='chat_avatars/default.png', upload_to='chat_avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего сообщения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=8, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_content',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='school.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=7, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Непрочитанные сообщения'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-last_message_at'], name='school_chat_last_me_6b5a21_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-created_at', 'chat'], name='school_chat_created_e95f71_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'sender'], name='school_chat_chat_id_6bffdf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', '-last_read_time'], name='school_chat_user_id_8cf80a_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'chat'), name='unique_participant'),
        ),
    ]
