# Generated by Django 5.2 on 2025-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_project_event_projecttask_studentevent_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий')], default='MEDIUM', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('COMPLETED', 'Завершённый')], default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role_in_project',
            field=models.CharField(choices=[('OWNER', 'Руководитель'), ('DEVELOPER', 'Разработчик'), ('DESIGNER', 'Дизайнер'), ('ANALYST', 'Аналитик')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Выполнена')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
