# Generated by Django 5.2 on 2025-05-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_category_news'),
        ('school', '0004_alter_project_priority_alter_project_status_and_more'),
    ]

    operations = [
    ]
