# Generated by Django 5.2 on 2025-05-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_chatmessage_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatparticipant',
            name='unique_participant',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='school_chat_last_me_6b5a21_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='school_chat_created_e95f71_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='school_chat_chat_id_6bffdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatparticipant',
            name='school_chat_user_id_8cf80a_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='chatparticipant',
            name='last_read_time',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_avatars/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=8),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='school.chat'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
