# Generated by Django 5.2 on 2025-05-03 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_chatparticipant_unique_participant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'Личный'), ('group', 'Групповой')], default='private', max_length=8),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_by', to='school.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник')], default='member', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('user', 'chat')},
        ),
    ]
