# Generated by Django 5.2 on 2025-05-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_chatmessage_is_read_chatmessage_read_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/chat_avatars/'),
        ),
    ]
